#!/usr/bin/env fish
#echo "#My Log: Old cat executables for bash and cmd environment have been renmaed to _cat for easy deprecation learnings of my own."
#echo "#My Log: Remember to use `bat` instead. Below output is from `bat `cli tool. ~ Unknown Guy."
#echo "######################################"
bat $argv
