#!/usr/bin/env fish
if docker ps -q | grep "" > /dev/null # This is interesting to know how it works but I don't know really . LOL
	docker kill (docker ps -q)
	echo #My Log:  Killed above running containers.
else
	echo "#My Log: No containers are running right now. ~ Unknown Guy"
end
#BACKUP LINE: docker kill $(docker ps -q) 
#Note: this file doesn't work with git-bash idk why!!
#This file works good as it is like above.
#For fish shell (if you are executing it from cli, you must use it like below)
# docker kill (docker ps -q)
# https://stackoverflow.com/questions/19211855/fish-equivalent-of-bash-command-notation
