#!/usr/bin/env fish
# only fish scripts has bug that we need to use _docker which is aliased to original /c/Program Files/Docker Toolbox/docker daemon, BUT BASH SCRIPTS WORK GREATLY AS IT IS.
# SO BASH ROCKS FOR NOW!! THOUGH BASH SCRIPTS HANGS IIRC AT WHEN <tab> after the script name(if the scripts as $* passed to it).
if _docker ps -q | grep "" > /dev/null # This is interesting to know how it works but I don't know really . LOL
	docker kill (_docker ps -q)
	echo #My Log:  Killed above running containers.
else
	echo "#My Log: No containers are running right now. ~ Unknown Guy"
end
#BACKUP LINE: docker kill $(docker ps -q) 
#Note: this file doesn't work with git-bash idk why!!
#This file works good as it is like above.
#For fish shell (if you are executing it from cli, you must use it like below)
# docker kill (docker ps -q)
# https://stackoverflow.com/questions/19211855/fish-equivalent-of-bash-command-notation
