#!/usr/bin/env fish
if _docker images | grep \\n > /dev/null
	docker rmi (_docker images -q)
	echo "#My Log: Removed all above images."
else
	echo "#My Log: No images are present locally. ~ Unknown Guy"
end
