#!/bin/bash
#Usage(Deprecated): javamon <filename without extension>
#nodemon -q -e java -x "javac $*.java && java $*"

t=${*%?????}
#echo $t #echoing complete file name
#echo $* #echoing only file name without extension.
nodemon --config /c/additionalPath/nodemon.json -q -e java -x "javac $* && java $t"


#Tip: Also, you can now use `jmon fileName.java` which is a subscript of javamon.

#Learning how string expansion works, FYI: use command `man bash` and search for Parameter Expansion topic to know more.
#Testing below
#t=$*
#s=java
#t=${t%?????}
