#!/bin/bash
#nodemon -q -e rs -x "rustc $*.rs && $*"
#Usage(dreprecated): rustmon <filename without extension>
#Also, now you can use `rmon fileName.rs` as rmon is a subscript of rustmon.


#Usage: rmon filename.rs
t=${*%???}
nodemon -q -e rs -x "rustc $* && $t"
